#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

REMOTE_HOST="${REMOTE_HOST:-49.233.22.119}"
REMOTE_USER="${REMOTE_USER:-ubuntu}"
SSH_KEY="${SSH_KEY:-gk.pem}"
REMOTE="${REMOTE_USER}@${REMOTE_HOST}"
RUN_GIT=0
COMMIT_MESSAGE="${COMMIT_MESSAGE:-Deploy production update}"

usage() {
  cat <<'USAGE'
Usage:
  scripts/deploy_prod.sh [--push] [--message "commit message"]

Environment overrides:
  REMOTE_HOST=49.233.22.119
  REMOTE_USER=ubuntu
  SSH_KEY=gk.pem

Examples:
  scripts/deploy_prod.sh
  scripts/deploy_prod.sh --push --message "Update recommendation page"

Notes:
  - The SSH key is only used locally with ssh/scp -i; it is never packaged.
  - --push runs: git add -A, git commit, git push.
  - Without --push, the script deploys your current local code only.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --push)
      RUN_GIT=1
      shift
      ;;
    --message|-m)
      COMMIT_MESSAGE="${2:?Missing commit message}"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing command: $1" >&2
    exit 1
  }
}

need_file() {
  [[ -f "$1" ]] || {
    echo "Missing file: $1" >&2
    exit 1
  }
}

need_cmd git
need_cmd ssh
need_cmd scp
need_cmd tar
need_cmd mvn
need_cmd pnpm
need_cmd python3

need_file "$SSH_KEY"
need_file "data/organized/modeling_outputs/specialized_rank_model_2026.csv"
need_file "data/organized/modeling_inputs/extracted_csv/shandong_score_rank_2026.csv"
need_file "data/organized/modeling_inputs/extracted_csv/shandong_2026_bachelor_3in1.csv"

chmod 600 "$SSH_KEY" >/dev/null 2>&1 || true

if [[ "$RUN_GIT" -eq 1 ]]; then
  echo "==> Committing and pushing current changes"
  git add -A
  if git diff --cached --quiet; then
    echo "No staged changes; skip commit."
  else
    git commit -m "$COMMIT_MESSAGE"
  fi
  git push
fi

GIT_SHA="$(git rev-parse --short HEAD 2>/dev/null || date +%Y%m%d%H%M%S)"
RELEASE_NAME="gaokao-release-${GIT_SHA}-$(date +%Y%m%d%H%M%S)"
BUILD_DIR="/tmp/${RELEASE_NAME}"
TARBALL="/tmp/${RELEASE_NAME}.tar.gz"

echo "==> Building backend"
mvn -f backend/pom.xml -pl admission-boot -am clean install -DskipTests
mvn -f backend/pom.xml -pl admission-boot package org.springframework.boot:spring-boot-maven-plugin:3.4.4:repackage -DskipTests

echo "==> Building frontend"
(
  cd frontend
  pnpm install --frozen-lockfile
  pnpm build:user
  pnpm --filter @gaokao/admin-web exec vite build --base=/admin/
)

echo "==> Preparing release package: ${TARBALL}"
rm -rf "$BUILD_DIR" "$TARBALL"
mkdir -p \
  "$BUILD_DIR/backend" \
  "$BUILD_DIR/frontend/user" \
  "$BUILD_DIR/frontend/admin" \
  "$BUILD_DIR/data/organized/modeling_outputs" \
  "$BUILD_DIR/deploy" \
  "$BUILD_DIR/sql"

cp backend/admission-boot/target/admission-boot-1.0.0-SNAPSHOT.jar "$BUILD_DIR/backend/gaokao-api.jar"
cp -R frontend/apps/user-web/dist/. "$BUILD_DIR/frontend/user/"
cp -R frontend/apps/admin-web/dist/. "$BUILD_DIR/frontend/admin/"
cp data/organized/modeling_outputs/specialized_rank_model_2026.csv "$BUILD_DIR/data/organized/modeling_outputs/"
if [[ -f data/organized/modeling_outputs/specialized_rank_model_2026.meta.json ]]; then
  cp data/organized/modeling_outputs/specialized_rank_model_2026.meta.json "$BUILD_DIR/data/organized/modeling_outputs/"
fi

python3 - <<'PY' > "$BUILD_DIR/sql/seed_score_rank_2026.sql"
import csv
from pathlib import Path

src = Path("data/organized/modeling_inputs/extracted_csv/shandong_score_rank_2026.csv")
rows = []
with src.open("r", encoding="utf-8-sig", newline="") as f:
    reader = csv.reader(f)
    for row in reader:
        if len(row) < 3:
            continue
        try:
            score = int(str(row[0]).strip())
            segment = int(str(row[1]).strip())
            cumulative = int(str(row[2]).strip())
        except ValueError:
            continue
        rows.append((score, segment, cumulative))

print("-- 2026 score-rank seed generated by scripts/deploy_prod.sh")
print("START TRANSACTION;")
print("SET @old_score_rank_version_id = (SELECT data_version_id FROM active_data_version WHERE data_type = 'SCORE_RANK' AND year = 2026 LIMIT 1);")
print("DELETE FROM active_data_version WHERE data_type = 'SCORE_RANK' AND year = 2026;")
print("DELETE FROM score_rank_segment WHERE data_version_id IN (SELECT id FROM data_version WHERE data_type = 'SCORE_RANK' AND year = 2026);")
print("DELETE FROM data_version WHERE data_type = 'SCORE_RANK' AND year = 2026;")
print(f"INSERT INTO data_version (data_type, year, version_no, status, row_count, published_by, published_at) VALUES ('SCORE_RANK', 2026, 1, 'PUBLISHED', {len(rows)}, 0, NOW());")
print("SET @score_rank_version_id = LAST_INSERT_ID();")
print("INSERT INTO active_data_version (data_type, year, data_version_id) VALUES ('SCORE_RANK', 2026, @score_rank_version_id);")
print("INSERT INTO score_rank_segment (data_version_id, year, score, cumulative_count, segment_count) VALUES")
values = [
    f"(@score_rank_version_id, 2026, {score}, {cumulative}, {segment})"
    for score, segment, cumulative in rows
]
print(",\n".join(values) + ";")
print("COMMIT;")
PY

python3 scripts/generate_undergraduate_seed_sql.py \
  --input data/organized/modeling_inputs/extracted_csv/shandong_2026_bachelor_3in1.csv \
  > "$BUILD_DIR/sql/seed_enrollment_plan_2026.sql"

cat > "$BUILD_DIR/deploy/application-prod.yml" <<'YAML'
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/admission_platform?socketTimeout=120000&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: admission
    password: admission123
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 5000ms
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    validate-on-migrate: true

logging:
  file:
    name: /var/log/gaokao/admission.log

app:
  specialized-model:
    path: /opt/gaokao/data/organized/modeling_outputs/specialized_rank_model_2026.csv
  security:
    jwt:
      secret: change-me-to-a-secure-random-secret-at-least-256-bits
      expiration-ms: 7200000
      refresh-expiration-ms: 604800000
    session:
      cookie-name: ADMISSION_SESSION
YAML

cat > "$BUILD_DIR/deploy/gaokao-api.service" <<'SERVICE'
[Unit]
Description=Gaokao Admission API
After=network.target mysql.service redis-server.service

[Service]
Type=simple
User=gaokao
Group=gaokao
WorkingDirectory=/opt/gaokao
ExecStart=/usr/bin/java -jar /opt/gaokao/app.jar --spring.profiles.active=prod --spring.config.additional-location=file:/opt/gaokao/config/
Restart=always
RestartSec=5
SuccessExitStatus=143

[Install]
WantedBy=multi-user.target
SERVICE

cat > "$BUILD_DIR/deploy/gaokao-nginx.conf" <<'NGINX'
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root /var/www/gaokao/user;
    index index.html;

    client_max_body_size 50m;

    location /api/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
    }

    location /admin/ {
        alias /var/www/gaokao/admin/;
        try_files $uri $uri/ /admin/index.html;
    }

    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
NGINX

cat > "$BUILD_DIR/deploy/install.sh" <<'INSTALL'
#!/usr/bin/env bash
set -euo pipefail

RELEASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export DEBIAN_FRONTEND=noninteractive

sudo apt-get update
sudo apt-get install -y openjdk-17-jre-headless mysql-server redis-server nginx

sudo systemctl enable --now mysql
sudo systemctl enable --now redis-server
sudo systemctl enable --now nginx

sudo mysql <<'SQL'
CREATE DATABASE IF NOT EXISTS admission_platform CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'admission'@'localhost' IDENTIFIED BY 'admission123';
CREATE USER IF NOT EXISTS 'admission'@'127.0.0.1' IDENTIFIED BY 'admission123';
GRANT ALL PRIVILEGES ON admission_platform.* TO 'admission'@'localhost';
GRANT ALL PRIVILEGES ON admission_platform.* TO 'admission'@'127.0.0.1';
FLUSH PRIVILEGES;
SQL

sudo useradd --system --home /opt/gaokao --shell /usr/sbin/nologin gaokao 2>/dev/null || true
sudo mkdir -p /opt/gaokao/config /opt/gaokao/data /var/log/gaokao /var/www/gaokao/user /var/www/gaokao/admin

sudo systemctl stop gaokao-api 2>/dev/null || true
sudo cp "$RELEASE_DIR/backend/gaokao-api.jar" /opt/gaokao/app.jar
sudo cp "$RELEASE_DIR/deploy/application-prod.yml" /opt/gaokao/config/application-prod.yml
sudo rm -rf /opt/gaokao/data/organized/modeling_outputs
sudo mkdir -p /opt/gaokao/data
sudo cp -R "$RELEASE_DIR/data/." /opt/gaokao/data/
sudo rm -rf /var/www/gaokao/user /var/www/gaokao/admin
sudo mkdir -p /var/www/gaokao/user /var/www/gaokao/admin
sudo cp -R "$RELEASE_DIR/frontend/user/." /var/www/gaokao/user/
sudo cp -R "$RELEASE_DIR/frontend/admin/." /var/www/gaokao/admin/

sudo chown -R gaokao:gaokao /opt/gaokao /var/log/gaokao
sudo chown -R www-data:www-data /var/www/gaokao

sudo cp "$RELEASE_DIR/deploy/gaokao-api.service" /etc/systemd/system/gaokao-api.service
sudo cp "$RELEASE_DIR/deploy/gaokao-nginx.conf" /etc/nginx/sites-available/gaokao
sudo ln -sf /etc/nginx/sites-available/gaokao /etc/nginx/sites-enabled/gaokao
sudo rm -f /etc/nginx/sites-enabled/default

sudo systemctl daemon-reload
sudo systemctl enable --now gaokao-api
sudo nginx -t
sudo systemctl restart nginx

echo "Waiting for backend..."
for i in $(seq 1 40); do
  if curl -fsS http://127.0.0.1:8080/api/v1/recommendations/search \
    -H 'Content-Type: application/json' \
    --data-raw '{"year":2026,"educationLevel":"VOCATIONAL","score":410,"rank":430178,"subjects":["历史","生物","地理"],"pageNo":1,"pageSize":1,"recommendationCount":1}' >/dev/null; then
    break
  fi
  if [[ "$i" -eq 40 ]]; then
    sudo journalctl -u gaokao-api -n 120 --no-pager
    exit 1
  fi
  sleep 3
done

mysql -u admission -padmission123 admission_platform < "$RELEASE_DIR/sql/seed_score_rank_2026.sql"
mysql -u admission -padmission123 admission_platform < "$RELEASE_DIR/sql/seed_enrollment_plan_2026.sql"

curl -fsS http://127.0.0.1:8080/api/v1/recommendations/search \
  -H 'Content-Type: application/json' \
  --data-raw '{"year":2026,"educationLevel":"VOCATIONAL","score":410,"rank":430178,"subjects":["历史","生物","地理"],"pageNo":1,"pageSize":1,"recommendationCount":1}' >/dev/null
curl -fsS http://127.0.0.1:8080/api/v1/recommendations/search \
  -H 'Content-Type: application/json' \
  --data-raw '{"year":2026,"educationLevel":"UNDERGRADUATE","score":520,"rank":140000,"subjects":["历史","生物","地理"],"pageNo":1,"pageSize":1,"recommendationCount":1}' >/dev/null
curl -fsS http://127.0.0.1/health

echo
echo "Deployment finished."
INSTALL
chmod +x "$BUILD_DIR/deploy/install.sh"

tar -C /tmp -czf "$TARBALL" "$RELEASE_NAME"

echo "==> Uploading release to ${REMOTE}"
scp -i "$SSH_KEY" "$TARBALL" "${REMOTE}:/tmp/"

echo "==> Installing on server"
ssh -i "$SSH_KEY" "$REMOTE" "set -e; rm -rf /tmp/${RELEASE_NAME}; tar -xzf /tmp/${RELEASE_NAME}.tar.gz -C /tmp; cd /tmp/${RELEASE_NAME}; bash deploy/install.sh"

echo "==> Verifying public endpoints"
curl --noproxy '*' -fsS "http://${REMOTE_HOST}/health"
curl --noproxy '*' -fsSI "http://${REMOTE_HOST}/" >/dev/null
curl --noproxy '*' -fsSI "http://${REMOTE_HOST}/admin/" >/dev/null
curl --noproxy '*' -fsS "http://${REMOTE_HOST}/api/v1/recommendations/search" \
  -H 'Content-Type: application/json' \
  --data-raw '{"year":2026,"educationLevel":"VOCATIONAL","score":410,"rank":430178,"subjects":["历史","生物","地理"],"pageNo":1,"pageSize":1,"recommendationCount":1}' >/dev/null
curl --noproxy '*' -fsS "http://${REMOTE_HOST}/api/v1/recommendations/search" \
  -H 'Content-Type: application/json' \
  --data-raw '{"year":2026,"educationLevel":"UNDERGRADUATE","score":520,"rank":140000,"subjects":["历史","生物","地理"],"pageNo":1,"pageSize":1,"recommendationCount":1}' >/dev/null

echo
echo "Done: http://${REMOTE_HOST}/"
echo "Admin: http://${REMOTE_HOST}/admin/"
